FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"
SRC_URI = "git://github.com/xbmc/inputstream.ffmpegdirect.git;protocol=https;branch=${KODICODENAME}"
#SRC_URI:append = " file://161.patch"
SRCREV = "${AUTOREV}"
PV = "${SRCPV}"
